# Generated by Django 4.1.1 on 2022-12-28 21:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0003_alter_chatmessages_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='room_channel',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='roomchannel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomchannel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomchannel',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_chatted']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_chatted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 21, 14, 32, 537453, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
