# Generated by Django 4.1.1 on 2022-12-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0006_alter_groupmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_chatted',
            field=models.DateTimeField(null=True),
        ),
    ]
