# Generated by Django 4.1.1 on 2023-01-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0008_file_chatmessages_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
