# Generated by Django 4.1.1 on 2023-01-03 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Socket', '0009_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='online',
            field=models.ManyToManyField(related_name='online', to=settings.AUTH_USER_MODEL),
        ),
    ]
